proxies:
- name: JP, Tokyo 2
  type: ss
  server: 13.231.248.146
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: KR, Incheon
  type: ss
  server: 18.182.6.88
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: TW, Taipei
  type: ss
  server: 52.195.215.236
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: HK, New Territories
  type: ss
  server: 57.180.31.56
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: US, Houston
  type: ss
  server: 35.91.100.155
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: HK, Kowloon
  type: ss
  server: 54.95.50.167
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: JP, Tokyo
  type: ss
  server: 18.177.145.228
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: CA, Vancouver
  type: ss
  server: 54.244.0.4
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: SG, Singapore
  type: ss
  server: 18.141.9.206
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: US, Dallas 2
  type: ss
  server: 34.220.99.193
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: JP, Osaka
  type: ss
  server: 13.125.187.128
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: HK, Los Angeles
  type: ss
  server: 44.243.110.63
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - JP, Tokyo 2
  - KR, Incheon
  - TW, Taipei
  - HK, New Territories
  - US, Houston
  - HK, Kowloon
  - JP, Tokyo
  - CA, Vancouver
  - SG, Singapore
  - US, Dallas 2
  - JP, Osaka
  - HK, Los Angeles
rules:
- DOMAIN-SUFFIX,google.com,PROXY
- DOMAIN-KEYWORD,youtube,PROXY
- GEOIP,CN,DIRECT
- MATCH,PROXY
