proxies:
- name: HK, New Territories
  type: ss
  server: 13.231.248.146
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: TW, Taipei
  type: ss
  server: 18.177.145.228
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: HK, Los Angeles
  type: ss
  server: 44.243.45.146
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: JP, Tokyo
  type: ss
  server: 52.194.186.197
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: KR, Incheon
  type: ss
  server: 18.182.6.88
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: JP, Osaka
  type: ss
  server: 43.206.216.94
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: SG, Singapore
  type: ss
  server: 35.77.85.254
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: US, Houston
  type: ss
  server: 54.244.0.4
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: CA, Vancouver
  type: ss
  server: 35.91.100.155
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: JP, Tokyo 2
  type: ss
  server: 13.125.199.67
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: US, Dallas 2
  type: ss
  server: 54.244.78.72
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
- name: HK, Kowloon
  type: ss
  server: 54.95.50.167
  port: '443'
  cipher: aes-256-cfb
  password: amazonskr05
  udp: true
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - HK, New Territories
  - TW, Taipei
  - HK, Los Angeles
  - JP, Tokyo
  - KR, Incheon
  - JP, Osaka
  - SG, Singapore
  - US, Houston
  - CA, Vancouver
  - JP, Tokyo 2
  - US, Dallas 2
  - HK, Kowloon
rules:
- DOMAIN-SUFFIX,google.com,PROXY
- DOMAIN-KEYWORD,youtube,PROXY
- GEOIP,CN,DIRECT
- MATCH,PROXY
