name: Update Clash Config

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间00:00运行
  workflow_dispatch:     # 允许手动触发

jobs:
  generate-config:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run generator
      env:
        GIST_ID: ${{ secrets.GIST_ID }}
        GIST_PAT: ${{ secrets.GIST_PAT }}
      run: python ss_generator.py
