name: Update Clash Config
on:
  schedule:
    - cron: '0 0 * * *'  # 每天00.00运行一次
  workflow_dispatch:        # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        env:
          GIST_LINK: ${{ secrets.GIST_LINK }}
          GIST_PAT: ${{ secrets.GIST_PAT }}
        run: python main.py
      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add clash.yaml
          git commit -m "Update clash.yaml" || exit 0
          git push
